### ISSUE TITLE
Habilitar envio de arquivos

### ISSUE THREAD

**Issue by hadiljr** [Astolfoho/WebChat#1]

**Comment by Astolfoho** [comment]
essa esta sendo a  feature mais pedida

**Comment by Astolfoho** [comment]
versao inicial de envio de arquivos ja funcionando

**Comment by Astolfoho** [comment]
versao inicial de envio de arquivos ja funcionando

**Comment by hadiljr** [comment]
Aeeee, agora da para enviar fotos.
